kind: ConfigMap
apiVersion: v1
metadata:
  name: checkin-service
  namespace: dev
data:
  application.yaml: |-

    server:
      port: 8070

    spring:
      application:
        name: checkin-service

      rabbitmq:
        addresses: rabbitmq
        username: guest
        password: guest

      datasource:
        url: jdbc:h2:mem:checkindb
        username: sa
        password:

      h2:
        console:
          enabled: true
      jpa:
        hibernate:
          ddl-auto: update

    logging:
      level:
        com:
          jdum:
            booking: INFO